export type BackgroundType = "transparent" | "color" | "gradient" | "image";

export interface BackgroundItem {
  id: string;
  nameId: string;
  nameEn: string;
  category: "flowers" | "nature" | "materials" | "gradients" | "colors" | "abstract" | "interiors";
  type: BackgroundType;
  value?: string; // hex color for 'color'
  stops?: { offset: number; color: string }[]; // for 'gradient'
  cssBackground?: string; // CSS style string for instant UI thumbnail preview
  url?: string; // image URL for 'image'
  fallbackColor?: string;
}

export interface BackgroundCategoryMeta {
  id: "all" | "flowers" | "nature" | "materials" | "gradients" | "colors" | "abstract" | "interiors";
  nameId: string;
  nameEn: string;
  icon: string;
}

export const BACKGROUND_CATEGORIES: BackgroundCategoryMeta[] = [
  { id: "all", nameId: "Semua", nameEn: "All", icon: "✨" },
  { id: "flowers", nameId: "Bunga & Flora", nameEn: "Flowers & Flora", icon: "🌸" },
  { id: "nature", nameId: "Alam & Pemandangan", nameEn: "Nature & Landscapes", icon: "🏞️" },
  { id: "materials", nameId: "Studio & Bahan", nameEn: "Studio & Materials", icon: "🏛️" },
  { id: "gradients", nameId: "Gradien Modern", nameEn: "Modern Gradients", icon: "🌈" },
  { id: "colors", nameId: "Warna Solid", nameEn: "Solid Colors", icon: "🎨" },
  { id: "abstract", nameId: "Abstrak & Efek", nameEn: "Abstract & Effects", icon: "🔮" },
  { id: "interiors", nameId: "Interior & Tempat", nameEn: "Interiors & Spaces", icon: "🏙️" },
];

export const BACKGROUND_CATALOG: BackgroundItem[] = [
  // =========================================================================
  // 0. TRANSPARENT (DEFAULT)
  // =========================================================================
  {
    id: "transparent",
    nameId: "Transparan (PNG)",
    nameEn: "Transparent (PNG)",
    category: "colors",
    type: "transparent",
    cssBackground: "repeating-conic-gradient(#334155 0% 25%, #1e293b 0% 50%) 50% / 12px 12px",
  },

  // =========================================================================
  // 1. BUNGA & FLORA (35+ PILIHAN)
  // =========================================================================
  {
    id: "flower_sakura_blossom",
    nameId: "Sakura Cherry Blossom",
    nameEn: "Cherry Blossom Bloom",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#ffd1dc",
  },
  {
    id: "flower_red_roses",
    nameId: "Bunga Mawar Merah",
    nameEn: "Velvet Red Roses",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#be123c",
  },
  {
    id: "flower_sunflower_meadow",
    nameId: "Kebun Bunga Matahari",
    nameEn: "Golden Sunflower Meadow",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#facc15",
  },
  {
    id: "flower_provence_lavender",
    nameId: "Padang Lavender Ungu",
    nameEn: "Provence Lavender Field",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#c084fc",
  },
  {
    id: "flower_tropical_monstera",
    nameId: "Daun Tropis Monstera",
    nameEn: "Tropical Monstera Leaves",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#065f46",
  },
  {
    id: "flower_white_orchids",
    nameId: "Anggrek Putih Elegan",
    nameEn: "Elegant White Orchids",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1567696911980-2eed69a46042?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#f8fafc",
  },
  {
    id: "flower_wildflower_bloom",
    nameId: "Bunga Liar Warna-Warni",
    nameEn: "Vibrant Wildflowers",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#f472b6",
  },
  {
    id: "flower_pink_peony",
    nameId: "Bunga Peony Merah Muda",
    nameEn: "Soft Pink Peonies",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#fbcfe8",
  },
  {
    id: "flower_daisy_meadow",
    nameId: "Hamparan Bunga Daisy",
    nameEn: "Fresh Daisy Field",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1469248647051-5768cf552ec7?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#fef08a",
  },
  {
    id: "flower_dutch_tulips",
    nameId: "Taman Tulip Belanda",
    nameEn: "Colorful Dutch Tulips",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1520763185298-1b434c919102?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#f43f5e",
  },
  {
    id: "flower_lotus_pond",
    nameId: "Kolam Bunga Teratai",
    nameEn: "Serene Lotus Pond",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1508615039623-a25605d2b022?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#fb7185",
  },
  {
    id: "flower_eucalyptus_leaves",
    nameId: "Daun Eukaliptus Sage",
    nameEn: "Aesthetic Eucalyptus",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#a7f3d0",
  },
  {
    id: "flower_hydrangea_pastel",
    nameId: "Bunga Hortensia Pastel",
    nameEn: "Pastel Hydrangeas",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#93c5fd",
  },
  {
    id: "flower_tropical_hibiscus",
    nameId: "Bunga Kembang Sepatu",
    nameEn: "Tropical Red Hibiscus",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1550950158-d0d960dff51b?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#e11d48",
  },
  {
    id: "flower_purple_lilac",
    nameId: "Bunga Lilac Harum",
    nameEn: "Fragrant Purple Lilac",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#d8b4fe",
  },
  {
    id: "flower_greenhouse_botanical",
    nameId: "Rumah Kaca Botani",
    nameEn: "Botanical Greenhouse",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1466781783364-36c955e42a7f?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#15803d",
  },
  {
    id: "flower_cherry_branch",
    nameId: "Dahan Bunga Sakura Estetik",
    nameEn: "Delicate Sakura Branch",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1528183429752-a97d0bf99b5a?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#fecdd3",
  },
  {
    id: "flower_crimson_dahlia",
    nameId: "Bunga Dahlia Mewah",
    nameEn: "Crimson Dahlia Bloom",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1508615070457-7baeba4003ab?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#9f1239",
  },
  {
    id: "flower_bluebell_forest",
    nameId: "Hutan Bunga Bluebell",
    nameEn: "Bluebell Woodland",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#60a5fa",
  },
  {
    id: "flower_pampas_grass",
    nameId: "Rumput Pampas Aesthetic",
    nameEn: "Dried Pampas Grass",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#d6d3d1",
  },
  {
    id: "flower_succulents_garden",
    nameId: "Tanaman Sukulen & Kaktus",
    nameEn: "Aesthetic Succulents",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#10b981",
  },
  {
    id: "flower_olive_branches",
    nameId: "Dahan Zaitun Minimalis",
    nameEn: "Mediterranean Olive Branches",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#84cc16",
  },
  {
    id: "flower_white_roses_flatlay",
    nameId: "Mawar Putih Flatlay",
    nameEn: "White Roses Bouquet",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1533616688419-b7a585564566?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#f1f5f9",
  },
  {
    id: "flower_autumn_leaves",
    nameId: "Dedaunan Gugur Emas",
    nameEn: "Golden Autumn Foliage",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#ea580c",
  },
  {
    id: "flower_fern_rainforest",
    nameId: "Pakis Hutan Hujan Segar",
    nameEn: "Lush Rainforest Ferns",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#047857",
  },
  {
    id: "flower_magnolia_white",
    nameId: "Bunga Magnolia Mewah",
    nameEn: "Pristine White Magnolia",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#e2e8f0",
  },
  {
    id: "flower_carnation_pastel",
    nameId: "Bunga Anyelir Pastel",
    nameEn: "Pastel Carnations",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#f472b6",
  },
  {
    id: "flower_poppy_red",
    nameId: "Bunga Poppy Merah Cerah",
    nameEn: "Red Poppy Meadow",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#dc2626",
  },
  {
    id: "flower_bamboo_foliage",
    nameId: "Rimbun Daun Bambu Zen",
    nameEn: "Zen Bamboo Foliage",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#16a34a",
  },
  {
    id: "flower_marigold_orange",
    nameId: "Bunga Marigold Jingga",
    nameEn: "Vibrant Orange Marigold",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1561181286-d3fee7d55364?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#f97316",
  },
  {
    id: "flower_cotton_plant",
    nameId: "Bunga Kapas Minimalis",
    nameEn: "White Cotton Stems",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#f1f5f9",
  },
  {
    id: "flower_vintage_botanical_plate",
    nameId: "Ilustrasi Botani Antik",
    nameEn: "Vintage Botanical Herbarium",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#fef3c7",
  },
  {
    id: "flower_cherry_petals_water",
    nameId: "Kelopak Bunga di Air",
    nameEn: "Floating Petals on Water",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#fda4af",
  },
  {
    id: "flower_golden_mimosa",
    nameId: "Bunga Mimosa Kuning",
    nameEn: "Yellow Mimosa Bloom",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#eab308",
  },
  {
    id: "flower_tropical_frangipani",
    nameId: "Bunga Kamboja Bali",
    nameEn: "Balinese Frangipani",
    category: "flowers",
    type: "image",
    url: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#fef08a",
  },

  // =========================================================================
  // 2. ALAM & PEMANDANGAN (35+ PILIHAN)
  // =========================================================================
  {
    id: "nature_sunset_beach",
    nameId: "Pantai Senja Sunset",
    nameEn: "Golden Sunset Beach",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#fdba74",
  },
  {
    id: "nature_turquoise_ocean",
    nameId: "Air Laut Biru Toska",
    nameEn: "Turquoise Tropical Ocean",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#06b6d4",
  },
  {
    id: "nature_swiss_alps",
    nameId: "Pegunungan Salju Alpin",
    nameEn: "Swiss Alps Snowy Peaks",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#e2e8f0",
  },
  {
    id: "nature_misty_pine_forest",
    nameId: "Hutan Pinus Berkabut",
    nameEn: "Misty Evergreen Pines",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#1e293b",
  },
  {
    id: "nature_sahara_dunes",
    nameId: "Gurun Pasir Sahara",
    nameEn: "Sahara Sand Dunes",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#f59e0b",
  },
  {
    id: "nature_aurora_borealis",
    nameId: "Aurora Cahaya Utara",
    nameEn: "Aurora Borealis Skies",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#10b981",
  },
  {
    id: "nature_waterfall_mist",
    nameId: "Air Terjun Alami Segar",
    nameEn: "Cascade Waterfall Mist",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#0284c7",
  },
  {
    id: "nature_starry_galaxy",
    nameId: "Galaksi Bintang Malam",
    nameEn: "Starry Night Milky Way",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#0f172a",
  },
  {
    id: "nature_emerald_lake",
    nameId: "Danau Zamrud Tenang",
    nameEn: "Emerald Mountain Lake",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#0d9488",
  },
  {
    id: "nature_canyon_sunset",
    nameId: "Lembah Ngarai Merah",
    nameEn: "Red Rock Canyon Sunset",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#c2410c",
  },
  {
    id: "nature_bamboo_zen_forest",
    nameId: "Hutan Bambu Arashiyama",
    nameEn: "Arashiyama Bamboo Forest",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#15803d",
  },
  {
    id: "nature_golden_meadow_sun",
    nameId: "Padang Rumput Emas Sore",
    nameEn: "Golden Hour Savanna",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#d97706",
  },
  {
    id: "nature_storm_cloudy_sky",
    nameId: "Langit Berawan Sinematik",
    nameEn: "Dramatic Cloudscape",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1534088568595-a066f410bcda?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#475569",
  },
  {
    id: "nature_autumn_river",
    nameId: "Sungai Hutan Musim Gugur",
    nameEn: "Autumn Forest River",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#b45309",
  },
  {
    id: "nature_tropical_palm_sunset",
    nameId: "Pohon Palem Siluet Sunset",
    nameEn: "Tropical Palm Silhouettes",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#f97316",
  },
  {
    id: "nature_mount_fuji",
    nameId: "Puncak Gunung Berapi",
    nameEn: "Majestic Volcano Peak",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#64748b",
  },
  {
    id: "nature_green_tea_terrace",
    nameId: "Kebun Teh Berundak",
    nameEn: "Green Tea Plantation",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#22c55e",
  },
  {
    id: "nature_nordic_fjord",
    nameId: "Fjord Laut Nordik",
    nameEn: "Nordic Sea Fjord",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#0369a1",
  },
  {
    id: "nature_crystal_cave",
    nameId: "Gua Es Kristal",
    nameEn: "Glacier Ice Cave",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#38bdf8",
  },
  {
    id: "nature_sunlit_underwater",
    nameId: "Cahaya Bawah Air Laut",
    nameEn: "Sunlit Underwater Caustics",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#0284c7",
  },
  {
    id: "nature_foggy_morning_lake",
    nameId: "Danau Pagi Berkabut",
    nameEn: "Misty Morning Lake",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1439853941329-a99ce0457e8a?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#94a3b8",
  },
  {
    id: "nature_rice_terrace_bali",
    nameId: "Sawah Terasering Ubud",
    nameEn: "Ubud Rice Terraces",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#16a34a",
  },
  {
    id: "nature_cloud_sea_summit",
    nameId: "Lautan Awan di Puncak",
    nameEn: "Sea of Clouds Summit",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#cbd5e1",
  },
  {
    id: "nature_iceland_black_sand",
    nameId: "Pantai Pasir Hitam Islandia",
    nameEn: "Iceland Black Sand Beach",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1489549132488-d00b7eee80f1?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#1e293b",
  },
  {
    id: "nature_pink_lake",
    nameId: "Danau Air Merah Muda",
    nameEn: "Pink Salt Lake",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#f472b6",
  },
  {
    id: "nature_rainbow_mountains",
    nameId: "Pegunungan Pelangi Zhangye",
    nameEn: "Rainbow Mountain Geologies",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#fb923c",
  },
  {
    id: "nature_rainy_window_city",
    nameId: "Rintik Hujan di Kaca",
    nameEn: "Raindrops on Glass Window",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#334155",
  },
  {
    id: "nature_sunflowers_sunset",
    nameId: "Bunga Matahari Saat Senja",
    nameEn: "Sunflowers at Golden Dusk",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#f59e0b",
  },
  {
    id: "nature_winter_snow_trees",
    nameId: "Salju Putih Pepohonan",
    nameEn: "Winter Snow Pine Forest",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1491002052546-bf38f186af56?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#e2e8f0",
  },
  {
    id: "nature_tropical_jungle_canopy",
    nameId: "Kanopi Hutan Tropis Lebat",
    nameEn: "Tropical Jungle Canopy",
    category: "nature",
    type: "image",
    url: "https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#14532d",
  },

  // =========================================================================
  // 3. STUDIO & MATERIAL BAHAN (30+ PILIHAN)
  // =========================================================================
  {
    id: "mat_white_carrara_marble",
    nameId: "Marmer Putih Carrara",
    nameEn: "Carrara White Marble",
    category: "materials",
    type: "image",
    url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#f1f5f9",
  },
  {
    id: "mat_black_gold_marble",
    nameId: "Marmer Hitam Urat Emas",
    nameEn: "Black Gold Veined Onyx",
    category: "materials",
    type: "image",
    url: "https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#0f172a",
  },
  {
    id: "mat_natural_warm_oak",
    nameId: "Kayu Oak Alami Hangat",
    nameEn: "Natural Warm Oak Wood",
    category: "materials",
    type: "image",
    url: "https://images.unsplash.com/photo-1546484396-fb3fc6f95f98?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#d97706",
  },
  {
    id: "mat_dark_walnut_wood",
    nameId: "Kayu Walnut Gelap Mewah",
    nameEn: "Luxury Dark Walnut",
    category: "materials",
    type: "image",
    url: "https://images.unsplash.com/photo-1543459176-4426b37223ba?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#78350f",
  },
  {
    id: "mat_brutalist_concrete",
    nameId: "Semen Beton Minimalis",
    nameEn: "Architectural Raw Concrete",
    category: "materials",
    type: "image",
    url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#64748b",
  },
  {
    id: "mat_white_terrazzo",
    nameId: "Batu Terrazzo Putih Estetik",
    nameEn: "Aesthetic White Terrazzo",
    category: "materials",
    type: "image",
    url: "https://images.unsplash.com/photo-1588854337236-6889d631faa8?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#e2e8f0",
  },
  {
    id: "mat_liquid_gold_silk",
    nameId: "Kain Sutra Emas Mengalir",
    nameEn: "Liquid Gold Silk Drape",
    category: "materials",
    type: "image",
    url: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#ca8a04",
  },
  {
    id: "mat_dark_velvet_crimson",
    nameId: "Beludru Merah Marun",
    nameEn: "Royal Crimson Velvet",
    category: "materials",
    type: "image",
    url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#881337",
  },
  {
    id: "mat_white_linen_fabric",
    nameId: "Kain Linen Katun Putih",
    nameEn: "Soft White Linen Fabric",
    category: "materials",
    type: "image",
    url: "https://images.unsplash.com/photo-1528458876861-544fd1761a91?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#f8fafc",
  },
  {
    id: "mat_brushed_titanium",
    nameId: "Logam Titanium Metalik",
    nameEn: "Brushed Titanium Metallic",
    category: "materials",
    type: "image",
    url: "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#475569",
  },
  {
    id: "mat_clean_studio_cyc",
    nameId: "Studio Putih Cyclorama",
    nameEn: "Studio White Infinite Cyc",
    category: "materials",
    type: "image",
    url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#ffffff",
  },
  {
    id: "mat_scandinavian_pine",
    nameId: "Kayu Pinus Skandinavia",
    nameEn: "Light Scandinavian Pine",
    category: "materials",
    type: "image",
    url: "https://images.unsplash.com/photo-1546484396-fb3fc6f95f98?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#fed7aa",
  },
  {
    id: "mat_terracotta_plaster",
    nameId: "Plester Dinding Terracotta",
    nameEn: "Warm Terracotta Plaster",
    category: "materials",
    type: "image",
    url: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#ea580c",
  },
  {
    id: "mat_subway_tiles_white",
    nameId: "Keramik Putih Glossy",
    nameEn: "White Ceramic Subway Tiles",
    category: "materials",
    type: "image",
    url: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#f1f5f9",
  },
  {
    id: "mat_emerald_green_marble",
    nameId: "Marmer Hijau Emerald",
    nameEn: "Verde Emerald Marble",
    category: "materials",
    type: "image",
    url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#065f46",
  },
  {
    id: "mat_cork_board_natural",
    nameId: "Papan Gabus Alami",
    nameEn: "Natural Cork Texture",
    category: "materials",
    type: "image",
    url: "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#d97706",
  },
  {
    id: "mat_carbon_fiber_dark",
    nameId: "Serat Karbon Hitam Tech",
    nameEn: "Dark Carbon Fiber Weave",
    category: "materials",
    type: "image",
    url: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#020617",
  },
  {
    id: "mat_slate_stone_textured",
    nameId: "Batu Slate Hitam Alami",
    nameEn: "Textured Black Slate Stone",
    category: "materials",
    type: "image",
    url: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#1e293b",
  },

  // =========================================================================
  // 4. GRADIEN MODERN & MESH (45+ PILIHAN)
  // =========================================================================
  {
    id: "grad_sunset_horizon",
    nameId: "Sunset Horizon",
    nameEn: "Sunset Horizon",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #ff7e5f 0%, #feb47b 100%)",
    stops: [
      { offset: 0, color: "#ff7e5f" },
      { offset: 1, color: "#feb47b" },
    ],
  },
  {
    id: "grad_cyberpunk_neon",
    nameId: "Neon Cyberpunk",
    nameEn: "Neon Cyberpunk",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #f72585 0%, #7209b7 50%, #4361ee 100%)",
    stops: [
      { offset: 0, color: "#f72585" },
      { offset: 0.5, color: "#7209b7" },
      { offset: 1, color: "#4361ee" },
    ],
  },
  {
    id: "grad_pastel_dream",
    nameId: "Pastel Dream Cloud",
    nameEn: "Pastel Dream Cloud",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #ffcbf2 0%, #e2e2ff 50%, #c8e7ff 100%)",
    stops: [
      { offset: 0, color: "#ffcbf2" },
      { offset: 0.5, color: "#e2e2ff" },
      { offset: 1, color: "#c8e7ff" },
    ],
  },
  {
    id: "grad_mystic_purple",
    nameId: "Mystic Violet Glow",
    nameEn: "Mystic Violet Glow",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #6a11cb 0%, #2575fc 100%)",
    stops: [
      { offset: 0, color: "#6a11cb" },
      { offset: 1, color: "#2575fc" },
    ],
  },
  {
    id: "grad_peach_sorbet",
    nameId: "Peach Sorbet Fresh",
    nameEn: "Peach Sorbet Fresh",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #fbc2eb 0%, #a6c1ee 100%)",
    stops: [
      { offset: 0, color: "#fbc2eb" },
      { offset: 1, color: "#a6c1ee" },
    ],
  },
  {
    id: "grad_cosmic_ocean",
    nameId: "Cosmic Deep Ocean",
    nameEn: "Cosmic Deep Ocean",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)",
    stops: [
      { offset: 0, color: "#0f2027" },
      { offset: 0.5, color: "#203a43" },
      { offset: 1, color: "#2c5364" },
    ],
  },
  {
    id: "grad_golden_hour_luxury",
    nameId: "Golden Hour Luxury",
    nameEn: "Golden Hour Luxury",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #f6d365 0%, #fda085 100%)",
    stops: [
      { offset: 0, color: "#f6d365" },
      { offset: 1, color: "#fda085" },
    ],
  },
  {
    id: "grad_aurora_emerald",
    nameId: "Emerald Aurora Mint",
    nameEn: "Emerald Aurora Mint",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #0ba360 0%, #3cba92 100%)",
    stops: [
      { offset: 0, color: "#0ba360" },
      { offset: 1, color: "#3cba92" },
    ],
  },
  {
    id: "grad_rose_gold_luster",
    nameId: "Rose Gold Luster",
    nameEn: "Rose Gold Luster",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #f43f5e 0%, #fb7185 50%, #fda4af 100%)",
    stops: [
      { offset: 0, color: "#f43f5e" },
      { offset: 0.5, color: "#fb7185" },
      { offset: 1, color: "#fda4af" },
    ],
  },
  {
    id: "grad_bubblegum_pink",
    nameId: "Bubblegum Pop",
    nameEn: "Bubblegum Pop",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #ff758c 0%, #ff7eb3 100%)",
    stops: [
      { offset: 0, color: "#ff758c" },
      { offset: 1, color: "#ff7eb3" },
    ],
  },
  {
    id: "grad_midnight_indigo",
    nameId: "Midnight Indigo",
    nameEn: "Midnight Indigo",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #1e1b4b 0%, #312e81 50%, #4338ca 100%)",
    stops: [
      { offset: 0, color: "#1e1b4b" },
      { offset: 0.5, color: "#312e81" },
      { offset: 1, color: "#4338ca" },
    ],
  },
  {
    id: "grad_deep_space_purple",
    nameId: "Deep Space Nebula",
    nameEn: "Deep Space Nebula",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #000428 0%, #004e92 100%)",
    stops: [
      { offset: 0, color: "#000428" },
      { offset: 1, color: "#004e92" },
    ],
  },
  {
    id: "grad_electric_lime",
    nameId: "Electric Lime Green",
    nameEn: "Electric Lime Green",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #84fab0 0%, #8fd3f4 100%)",
    stops: [
      { offset: 0, color: "#84fab0" },
      { offset: 1, color: "#8fd3f4" },
    ],
  },
  {
    id: "grad_royal_amber",
    nameId: "Royal Amber Glow",
    nameEn: "Royal Amber Glow",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #f12711 0%, #f5af19 100%)",
    stops: [
      { offset: 0, color: "#f12711" },
      { offset: 1, color: "#f5af19" },
    ],
  },
  {
    id: "grad_holographic_silver",
    nameId: "Holographic Silver",
    nameEn: "Holographic Silver",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #e0eafc 0%, #cfdef3 100%)",
    stops: [
      { offset: 0, color: "#e0eafc" },
      { offset: 1, color: "#cfdef3" },
    ],
  },
  {
    id: "grad_velvet_plum",
    nameId: "Velvet Plum Berry",
    nameEn: "Velvet Plum Berry",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #5b247a 0%, #1bcedf 100%)",
    stops: [
      { offset: 0, color: "#5b247a" },
      { offset: 1, color: "#1bcedf" },
    ],
  },
  {
    id: "grad_sweet_morning",
    nameId: "Sweet Morning Light",
    nameEn: "Sweet Morning Light",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #ff9a9e 0%, #fecfef 99%, #fecfef 100%)",
    stops: [
      { offset: 0, color: "#ff9a9e" },
      { offset: 1, color: "#fecfef" },
    ],
  },
  {
    id: "grad_aqua_marine",
    nameId: "Aqua Marine Splash",
    nameEn: "Aqua Marine Splash",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #13547a 0%, #80d0c7 100%)",
    stops: [
      { offset: 0, color: "#13547a" },
      { offset: 1, color: "#80d0c7" },
    ],
  },
  {
    id: "grad_cherry_blossom",
    nameId: "Cherry Blossom Gradient",
    nameEn: "Cherry Blossom Gradient",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #fbc2eb 0%, #a18cd1 100%)",
    stops: [
      { offset: 0, color: "#fbc2eb" },
      { offset: 1, color: "#a18cd1" },
    ],
  },
  {
    id: "grad_dark_matter",
    nameId: "Dark Matter Carbon",
    nameEn: "Dark Matter Carbon",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #141e30 0%, #243b55 100%)",
    stops: [
      { offset: 0, color: "#141e30" },
      { offset: 1, color: "#243b55" },
    ],
  },
  {
    id: "grad_warm_flame",
    nameId: "Warm Radiant Flame",
    nameEn: "Warm Radiant Flame",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #ff0844 0%, #ffb199 100%)",
    stops: [
      { offset: 0, color: "#ff0844" },
      { offset: 1, color: "#ffb199" },
    ],
  },
  {
    id: "grad_lavender_mist",
    nameId: "Soft Lavender Mist",
    nameEn: "Soft Lavender Mist",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #cdb4db 0%, #ffcbf2 100%)",
    stops: [
      { offset: 0, color: "#cdb4db" },
      { offset: 1, color: "#ffcbf2" },
    ],
  },
  {
    id: "grad_lemon_twist",
    nameId: "Lemon Lime Twist",
    nameEn: "Lemon Lime Twist",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #38ef7d 0%, #11998e 100%)",
    stops: [
      { offset: 0, color: "#38ef7d" },
      { offset: 1, color: "#11998e" },
    ],
  },
  {
    id: "grad_nordic_frost",
    nameId: "Nordic Frost Ice",
    nameEn: "Nordic Frost Ice",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #00c6ff 0%, #0072ff 100%)",
    stops: [
      { offset: 0, color: "#00c6ff" },
      { offset: 1, color: "#0072ff" },
    ],
  },
  {
    id: "grad_copper_lux",
    nameId: "Copper Rust Glow",
    nameEn: "Copper Rust Glow",
    category: "gradients",
    type: "gradient",
    cssBackground: "linear-gradient(135deg, #b92b27 0%, #1565c0 100%)",
    stops: [
      { offset: 0, color: "#b92b27" },
      { offset: 1, color: "#1565c0" },
    ],
  },

  // =========================================================================
  // 5. WARNA SOLID LENGKAP: PASTEL, NEUTRAL, VIBRANT (60+ PILIHAN)
  // =========================================================================
  // Essentials & Neutrals
  { id: "col_pure_white", nameId: "Putih Murni Katalog", nameEn: "Pure White Catalog", category: "colors", type: "color", value: "#ffffff" },
  { id: "col_soft_ivory", nameId: "Ivory Gading Lembut", nameEn: "Soft Ivory White", category: "colors", type: "color", value: "#fafaf9" },
  { id: "col_cream_warm", nameId: "Krem Hangat Estetik", nameEn: "Warm Cream", category: "colors", type: "color", value: "#fef3c7" },
  { id: "col_dark_slate", nameId: "Hitam Slate Mewah", nameEn: "Dark Luxury Slate", category: "colors", type: "color", value: "#0f172a" },
  { id: "col_pitch_black", nameId: "Hitam Pekat Obsidian", nameEn: "Pitch Black", category: "colors", type: "color", value: "#000000" },
  { id: "col_charcoal_gray", nameId: "Abu-Abu Arang Charcoal", nameEn: "Charcoal Gray", category: "colors", type: "color", value: "#1f2937" },
  { id: "col_neutral_gray", nameId: "Abu Studio Netral", nameEn: "Neutral Studio Gray", category: "colors", type: "color", value: "#6b7280" },
  { id: "col_light_silver", nameId: "Perak Dingin Lembut", nameEn: "Light Cool Silver", category: "colors", type: "color", value: "#e5e7eb" },

  // Aesthetic Pastels
  { id: "col_pastel_pink", nameId: "Pastel Pink Blossom", nameEn: "Pastel Pink Blossom", category: "colors", type: "color", value: "#fce7f3" },
  { id: "col_powder_blue", nameId: "Powder Blue Lembut", nameEn: "Powder Baby Blue", category: "colors", type: "color", value: "#e0f2fe" },
  { id: "col_sage_green", nameId: "Sage Green Daun", nameEn: "Sage Green Herb", category: "colors", type: "color", value: "#dcfce7" },
  { id: "col_lavender_soft", nameId: "Lavender Ungu Manis", nameEn: "Sweet Lavender Pastel", category: "colors", type: "color", value: "#f3e8ff" },
  { id: "col_peach_puff", nameId: "Peach Segar Lembut", nameEn: "Soft Peach Puff", category: "colors", type: "color", value: "#ffedd5" },
  { id: "col_butter_yellow", nameId: "Kuning Mentega Hangat", nameEn: "Butter Yellow Pastel", category: "colors", type: "color", value: "#fef9c3" },
  { id: "col_mint_leaf", nameId: "Mint Hijau Dingin", nameEn: "Cool Mint Leaf", category: "colors", type: "color", value: "#ccfbf1" },
  { id: "col_muted_coral", nameId: "Coral Redup Elegan", nameEn: "Muted Coral Pastel", category: "colors", type: "color", value: "#ffe4e6" },
  { id: "col_dusty_rose", nameId: "Dusty Rose Vintage", nameEn: "Dusty Rose Vintage", category: "colors", type: "color", value: "#fbcfe8" },
  { id: "col_periwinkle", nameId: "Periwinkle Biru Ungu", nameEn: "Periwinkle Blue", category: "colors", type: "color", value: "#e0e7ff" },
  { id: "col_warm_sand", nameId: "Pasir Pantai Hangat", nameEn: "Warm Beach Sand", category: "colors", type: "color", value: "#f5f5f4" },
  { id: "col_apricot_light", nameId: "Apricot Lembut", nameEn: "Soft Light Apricot", category: "colors", type: "color", value: "#fed7aa" },

  // Earthy & Warm Tones
  { id: "col_terracotta_earth", nameId: "Terracotta Tanah Liat", nameEn: "Earthy Terracotta", category: "colors", type: "color", value: "#c2410c" },
  { id: "col_clay_beige", nameId: "Tanah Liat Beige", nameEn: "Warm Clay Beige", category: "colors", type: "color", value: "#d6d3d1" },
  { id: "col_olive_drab", nameId: "Hijau Zaitun Alami", nameEn: "Natural Olive Drab", category: "colors", type: "color", value: "#4d7c0f" },
  { id: "col_forest_deep", nameId: "Hijau Hutan Rimba", nameEn: "Deep Forest Green", category: "colors", type: "color", value: "#14532d" },
  { id: "col_coffee_brown", nameId: "Kopi Moka Hangat", nameEn: "Warm Coffee Brown", category: "colors", type: "color", value: "#78350f" },
  { id: "col_rich_espresso", nameId: "Espresso Gelap Mewah", nameEn: "Rich Dark Espresso", category: "colors", type: "color", value: "#451a03" },
  { id: "col_burnt_sienna", nameId: "Sienna Bata Bakar", nameEn: "Burnt Sienna", category: "colors", type: "color", value: "#9a3412" },
  { id: "col_desert_ochre", nameId: "Kuning Oker Gurun", nameEn: "Desert Ochre Gold", category: "colors", type: "color", value: "#b45309" },
  { id: "col_warm_taupe", nameId: "Taupe Lembut Elegan", nameEn: "Warm Taupe Gray", category: "colors", type: "color", value: "#a8a29e" },
  { id: "col_mustard_vintage", nameId: "Kuning Mustard Retro", nameEn: "Vintage Mustard", category: "colors", type: "color", value: "#ca8a04" },

  // Vivid & Commercial Bold
  { id: "col_electric_blue", nameId: "Biru Elektrik Menonjol", nameEn: "Electric Cobalt Blue", category: "colors", type: "color", value: "#2563eb" },
  { id: "col_ferrari_red", nameId: "Merah Menyala Berani", nameEn: "Bold Ferrari Red", category: "colors", type: "color", value: "#dc2626" },
  { id: "col_hot_magenta", nameId: "Magenta Neon Terang", nameEn: "Hot Neon Magenta", category: "colors", type: "color", value: "#db2777" },
  { id: "col_canary_yellow", nameId: "Kuning Cerah Menyala", nameEn: "Bright Canary Yellow", category: "colors", type: "color", value: "#facc15" },
  { id: "col_emerald_vibrant", nameId: "Hijau Zamrud Mewah", nameEn: "Vibrant Emerald", category: "colors", type: "color", value: "#059669" },
  { id: "col_royal_purple", nameId: "Ungu Kerajaan Glamor", nameEn: "Royal Purple Glamour", category: "colors", type: "color", value: "#7c3aed" },
  { id: "col_tangerine_orange", nameId: "Oranye Jeruk Segar", nameEn: "Fresh Tangerine Orange", category: "colors", type: "color", value: "#ea580c" },
  { id: "col_cyan_aqua", nameId: "Biru Cyan Kristal", nameEn: "Crystal Cyan Blue", category: "colors", type: "color", value: "#06b6d4" },
  { id: "col_indigo_deep", nameId: "Biru Indigo Elegan", nameEn: "Deep Royal Indigo", category: "colors", type: "color", value: "#4338ca" },
  { id: "col_teal_ocean", nameId: "Hijau Teal Samudra", nameEn: "Deep Ocean Teal", category: "colors", type: "color", value: "#0f766e" },

  // =========================================================================
  // 6. ABSTRAK & EFEK ESTETIK (25+ PILIHAN)
  // =========================================================================
  {
    id: "abs_golden_bokeh",
    nameId: "Kilau Lampu Bokeh Emas",
    nameEn: "Golden Bokeh Sparkles",
    category: "abstract",
    type: "image",
    url: "https://images.unsplash.com/photo-1519751138087-5bf79df62d5b?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#ca8a04",
  },
  {
    id: "abs_water_ripple",
    nameId: "Gelombang Air Segar",
    nameEn: "Crystal Water Caustics",
    category: "abstract",
    type: "image",
    url: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#0284c7",
  },
  {
    id: "abs_pastel_watercolor",
    nameId: "Cat Air Pastel Abstrak",
    nameEn: "Pastel Watercolor Wash",
    category: "abstract",
    type: "image",
    url: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#f472b6",
  },
  {
    id: "abs_holographic_foil",
    nameId: "Foil Holografik Berkilau",
    nameEn: "Iridescent Holographic Foil",
    category: "abstract",
    type: "image",
    url: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#a855f7",
  },
  {
    id: "abs_vintage_parchment",
    nameId: "Kertas Perkamen Antik",
    nameEn: "Vintage Textured Parchment",
    category: "abstract",
    type: "image",
    url: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#fef3c7",
  },
  {
    id: "abs_cyber_grid_neon",
    nameId: "Kisi-Kisi Grid Cyber 3D",
    nameEn: "3D Cyber Neon Grid",
    category: "abstract",
    type: "image",
    url: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#1e1b4b",
  },
  {
    id: "abs_smoke_whisp_dark",
    nameId: "Asap Halus Siluet Hitam",
    nameEn: "Wispy Atmospheric Smoke",
    category: "abstract",
    type: "image",
    url: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#020617",
  },
  {
    id: "abs_terrazzo_speckles",
    nameId: "Pola Bintik Terrazzo",
    nameEn: "Modern Terrazzo Speckles",
    category: "abstract",
    type: "image",
    url: "https://images.unsplash.com/photo-1588854337236-6889d631faa8?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#e2e8f0",
  },
  {
    id: "abs_acrylic_paint_pour",
    nameId: "Lukisan Akrilik Mengalir",
    nameEn: "Fluid Acrylic Paint Pour",
    category: "abstract",
    type: "image",
    url: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#ec4899",
  },
  {
    id: "abs_geometric_prism",
    nameId: "Prisma Cahaya Geometris",
    nameEn: "Geometric Light Prism",
    category: "abstract",
    type: "image",
    url: "https://images.unsplash.com/photo-1507499739999-097706ad8914?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#38bdf8",
  },
  {
    id: "abs_minimalist_window_shadow",
    nameId: "Bayangan Jendela Arsitektur",
    nameEn: "Aesthetic Window Shadow",
    category: "abstract",
    type: "image",
    url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#f1f5f9",
  },

  // =========================================================================
  // 7. INTERIOR & TEMPAT ARSITEKTUR (20+ PILIHAN)
  // =========================================================================
  {
    id: "int_aesthetic_cafe",
    nameId: "Interior Cafe Minimalis",
    nameEn: "Minimalist Aesthetic Cafe",
    category: "interiors",
    type: "image",
    url: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#d97706",
  },
  {
    id: "int_scandinavian_living",
    nameId: "Ruang Tamu Skandinavia",
    nameEn: "Nordic Living Room",
    category: "interiors",
    type: "image",
    url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#e2e8f0",
  },
  {
    id: "int_modern_kitchen_marble",
    nameId: "Meja Dapur Marmer Bersih",
    nameEn: "Modern Clean Marble Kitchen",
    category: "interiors",
    type: "image",
    url: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#f8fafc",
  },
  {
    id: "int_art_gallery_wall",
    nameId: "Dinding Galeri Seni Mewah",
    nameEn: "Minimalist Art Gallery Wall",
    category: "interiors",
    type: "image",
    url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#f1f5f9",
  },
  {
    id: "int_tokyo_city_night",
    nameId: "Gemerlap Kota Malam Tokyo",
    nameEn: "Bustling Tokyo City Lights",
    category: "interiors",
    type: "image",
    url: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#1e1b4b",
  },
  {
    id: "int_cozy_bookshelf_wood",
    nameId: "Rak Buku Kayu Estetik",
    nameEn: "Warm Wooden Library Shelves",
    category: "interiors",
    type: "image",
    url: "https://images.unsplash.com/photo-1507842229452-78927a7605d3?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#78350f",
  },
  {
    id: "int_luxury_penthouse_window",
    nameId: "Jendela Penthouse Mewah",
    nameEn: "Luxury Penthouse Skyline",
    category: "interiors",
    type: "image",
    url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#0f172a",
  },
  {
    id: "int_sunlit_designer_desk",
    nameId: "Meja Kerja Arsitek Bersih",
    nameEn: "Sunlit Designer Workspace",
    category: "interiors",
    type: "image",
    url: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
    fallbackColor: "#f1f5f9",
  },
];
